version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./ml_engine:/app/ml_engine
      # Mount data folder so user can drop files easily
      - ./ml_engine/data:/app/ml_engine/data
    environment:
      - PYTHONPATH=/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
